---
title: "Ordinary Differential Equations"
---

<!--Welcome to **Ordinary Differential Equations**!

I am delighted to have you in this course. Throughout the semester, we will develop the mathematical theory of ordinary differential equations while emphasizing intuition, analytical techniques, and applications arising in science, engineering, and other quantitative disciplines.-->

<!--This website will serve as the main hub for the course. Here you will find lecture notes, Jupyter notebooks, assignments, announcements, and additional resources. Please check this page regularly, as course materials and updates will be posted throughout the semester.

I encourage you to ask questions, participate actively in class, and enjoy the process of learning. I look forward to a productive and enjoyable semester together. Welcome!-->





| | |
|---|---|
| **Semester** | Third Semester |
| **Academic Period** | August 17 – December 5, 2026 |
| **Class Schedule** | Mon - Wed, 11:30 - 2:00 pm |
| **Classroom** | 218 |
| **Email** | <luisa.daza@im.unam.mx> |
| **Office Hours** | Fridays, 9:00 AM – 1:00 PM (or by appointment via email) |
| **Office** | Institute of Mathematics, UNAM Cuernavaca, Office N2 8 |

---

## Course Materials

- 📄 [Syllabus](./downloads/EDO2027I_Syllabus.pdf)
- 📒 [Lecture 1 - August 17, 2026](./downloads/Lecture1.pdf)
- 📒 [Lecture 2 - August 24, 2026](./downloads/Lecture2.pdf)
- 💻 [Homework 1](./downloads/Homework1.pdf)
- 💻 [Homework 2](./downloads/Homework2.pdf)

---

## Announcements

**4 de septiembre de 2026**

Es obligatorio registrarse en el siguiente formulario **por cada curso que tomen en el Instituto de Matemáticas**:

[Formulario de registro](https://fw.matcuer.unam.mx/UCIMAdmin/cae/ClasesLicenciatura)

A partir de estos registros se elaborará la lista de estudiantes de la UAEM autorizados para ingresar a la Unidad. Esta lista será utilizada por el personal de la entrada para permitirles el acceso.

Tomen en cuenta las siguientes indicaciones:

* Podrán ingresar a la Unidad desde **30 minutos antes del inicio de su clase**.
* Deberán retirarse **a más tardar 30 minutos después de que termine su clase**.

**Importante:** si no completan el formulario, no se les permitirá el acceso a la Unidad.







